# Generated by Django 3.2.9 on 2022-06-09 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category_slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='postsImage')),
                ('description', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 9, 13, 40, 37, 562096))),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 9, 13, 40, 37, 562096))),
                ('categories', models.ManyToManyField(blank=True, to='posts.Category')),
            ],
        ),
    ]
