# Generated by Django 3.2.9 on 2022-06-12 11:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutrition_record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition_record',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 12, 14, 47, 49, 485638)),
        ),
        migrations.AlterField(
            model_name='nutrition_record',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 12, 14, 47, 49, 485638)),
        ),
        migrations.AlterField(
            model_name='nutrition_record',
            name='user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
